import './globals.css'
import { Inter } from 'next/font/google'
import Nav from '@/components/Nav'
import Footer from '@/components/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'aapi website',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
      <html lang="en">
        <body className={`${inter.className} bg-amber-400 min-h-fit text-slate-100`}>
          <Nav />
          <main className = ''>
          {children}
          </main>
          <Footer />
        </body>
      </html>
    </>
  )
}
